### ISSUE TITLE
The facebook site is not displaying a proper login page

### ISSUE THREAD

**Issue by SanithSamaraweera2002** [x3rz/blackeye#12]

**Comment by SanithSamaraweera2002** [comment]
It is very different from the legit page. Please check

**Comment by j-dogcoder** [comment]
Hi there. The developer who owns this project seems to have other focuses these days. If you would like, check out the new version of this that we have in development. https://github.com/j-dogcoder/Blackeye-2.0. You are welcome to submit an issue there also. We are still finding a good team of developers, so we may not get on it right away. But we will do our best to get there as soon as we can.

**Comment by j-dogcoder** [comment]
@SanithSamaraweera2002 On our new version, Facebook is fixed and running. Go check it out!

**Comment by j-dogcoder** [comment]
Or it will be in the next commit that should go up this soon

**Comment by SanithSamaraweera2002** [comment]
I still can't get the legit website to work. Looking forward to hearing
from you soon. Thank you

**Comment by appstr** [comment]
The Facebook login page is missing CSS.

**Comment by xaviermarcus** [comment]
+1 on this
